apiVersion: apps/v1
kind: Deployment
metadata:
  name: jmeter-slaves
  labels:
    jmeter_mode: slave
spec:
  replicas: 1
  selector:
    matchLabels:
      jmeter_mode: slave
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        jmeter_mode: slave
    spec:
      containers:
        - name: jmslave
          image: docker-registry.c-43f6b45.kyma.ondemand.com/jmeter-slave-kyma:0.1
          # imagePullPolicy: Always
          imagePullPolicy: IfNotPresent
          # imagePullPolicy: Never
          ports:
            - containerPort: 1099
            - containerPort: 50000
          # resources:
          #   requests:
          #     cpu: 1024m
          #     memory: 1Gi
          #   limits:
          #     cpu: 1024m
          #     memory: 1Gi
