apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: jmeter-master
  labels:
    jmeter_mode: master
spec:
  replicas: 1
  selector:
    matchLabels:
      jmeter_mode: master
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        jmeter_mode: master
    spec:
      containers:
        - name: jmmaster
          image: docker-registry.c-43f6b45.kyma.ondemand.com/jmeter-master-kyma:0.1
          # imagePullPolicy: Always
          imagePullPolicy: IfNotPresent
          # imagePullPolicy: Never
          command: ["/bin/bash", "-c", "--"]
          args: ["while true; do sleep 30; done;"]
          volumeMounts:
            - name: loadtest
              mountPath: /load_test
              subPath: "load_test"
          ports:
            - containerPort: 60000
          # resources:
          #   requests:
          #     cpu: 100m
          #     memory: 1Gi
          #   limits:
          #     cpu: 1000m
          #     memory: 1Gi
      nodeName: ip-10-250-22-145.eu-central-1.compute.internal
      volumes:
        - name: loadtest
          configMap:
            name: jmeter-load-test
